[imaging_specs]
local_storage_directory = "D:\\"
external_storage_directory = "Z:\\stage\\exaSPIM"
subject_id = "651895"
tile_prefix = "tile"
tile_overlap_x_percent = 15
tile_overlap_y_percent = 15
z_step_size_um = 1
volume_x_um = 40000
volume_y_um = 20000
volume_z_um = 28672
laser_wavelengths = [ 488,]
start_tile_index = 0
end_tile_index = 14

[experiment_specs]
experimenters_name = "Xiaoyun Jiang"
immersion_medium = "0.05X SSC"
immersion_medium_refractive_index = 1.33
x_anatomical_direction = "Anterior_to_posterior"
y_anatomical_direction = "Inferior_to_superior"
z_anatomical_direction = "Left_to_right"

[design_specs]
slit_width_pixels = 480.0

[waveform_specs]
ttl_pulse_time_s = 0.01
frame_rest_time_s = 0.05

[compressor_specs]
image_stack_chunk_size = 64
compressor_thread_count = 32
compression_style = "lz4"

[file_transfer_specs]
protocol = "xcopy"
protocol_flags = "/j/i/y"

[camera_specs]
egrabber_frame_buffer = 8
unpacking_mode = "Msb"
digital_gain_adu = 1
line_interval_us = 45.44

[tile_specs]
x_field_of_view_um = 10615.616
y_field_of_view_um = 7958.72
row_count_pixels = 10640
column_count_pixels = 14192
data_type = "uint16"

[sample_stage_specs]
backlash_reset_distance_um = 4

[daq_driver_kwds]
dev_name = "Dev3"
samples_per_sec = 10000.0
livestream_frequency_hz = 15

[tiger_controller_driver_kwds]
com_port = "COM3"

[estimates]

[daq_driver_kwds.ao_channels]
etl = 0
camera = 1
stage = 2
488 = 5
638 = 3
561 = 4
405 = 6
galvo_a = 17
galvo_b = 19

[channel_specs.488]
driver = "Oxxius"
color = "blue"
hex_color = "#00ff92"
ao_channel = 3
ao_voltage = 10.0

[channel_specs.561]
driver = "Oxxius"
color = "yellowgreen"
hex_color = "#c6ff00"
ao_channel = 5
ao_voltage = 10.0

[channel_specs.405]
driver = "exaspim.devices.aotf_laser"
module = "AOTFLaser"
color = "purple"
hex_color = "#000000"
ao_channel = 6
ao_voltage = 10.0

[channel_specs.405.kwds]
wl = '405'
cfg = 'self.cfg'

[channel_specs.488.kwds]
wl = '488'
cfg = 'self.cfg'

[channel_specs.561.kwds]
wl = '561'
cfg = 'self.cfg'

[channel_specs.638.kwds]
wl = '638'
cfg = 'self.cfg'

[channel_specs.638]
driver = "Oxxius"
color = "red"
hex_color = "#000000"
ao_channel = 4
ao_voltage = 10.0

[joystick_kwds.axis_map]
x = 2
y = 3
z = 22

[sample_pose_kwds.axis_map]
x = "y"
y = "z"
z = "x"

[channel_specs.488.camera]
delay_time_s = 0

[channel_specs.488.etl]
amplitude = 0.123
offset = 2.437
nonlinear = 0.0
interp_time_s = 0.51
buffer_time_s = 0.05

[channel_specs.488.galvo_a]
setpoint = -0.01

[channel_specs.488.galvo_b]
setpoint = -0.01

[channel_specs.488.kwds]
port = "COMxx"

[channel_specs.561.camera]
delay_time_s = 0

[channel_specs.561.etl]
amplitude = 0.121
offset = 2.431
nonlinear = 0.0
interp_time_s = 0.5
buffer_time_s = 0.05

[channel_specs.561.galvo_a]
setpoint = 0

[channel_specs.561.galvo_b]
setpoint = 0

[channel_specs.561.kwds]
port = "COMxx"

[channel_specs.405.camera]
delay_time_s = 0

[channel_specs.405.etl]
amplitude = 0.173
offset = 2.342
nonlinear = 0.0
interp_time_s = 0.5
buffer_time_s = 0.05

[channel_specs.405.galvo_a]
setpoint = -0.5

[channel_specs.405.galvo_b]
setpoint = -0.5

[channel_specs.638.camera]
delay_time_s = 0

[channel_specs.638.etl]
amplitude = 0.173
offset = 2.348
nonlinear = 0.0
interp_time_s = 0.5
buffer_time_s = 0.05

[channel_specs.638.galvo_a]
setpoint = 0

[channel_specs.638.galvo_b]
setpoint = 0

[channel_specs.638.kwds]
port = "COMxx"
