[imaging_specs]
local_storage_directory = "D:\\"
external_storage_directory = "Y:\\"
subject_id = "test_exaspim"
tile_prefix = "tile"
tile_overlap_x_percent = 15
tile_overlap_y_percent = 15
z_step_size_um = 1
volume_x_um = 10000.0
volume_y_um = 7958.72
volume_z_um = 20000
laser_wavelengths = [ 488, 561, 638, 405,]

[design_specs]
slit_width_pixels = 333.3
column_count_pixels = 3000

[waveform_specs]
ttl_pulse_time_s = 0.01
frame_rest_time_s = 0.05
buffer_time_s = 0.05

[compressor_specs]
memento_executable_path = "C:\\Program Files\\Euresys\\Mementox08in\\86_64\\memento.exe"
image_stack_chunk_size = 64
compressor_thread_count = 32
compression_style = "lz4"

[file_transfer_specs]
protocol = "xcopy"
protocol_flags = "/j/i/y"

[camera_specs]
egrabber_frame_buffer = 8
unpacking_mode = "Msb"
autoscale = false
method = "Full"
digital_gain_adu = 1
line_interval_us = 15

[tile_specs]
x_field_of_view_um = 10615.616
y_field_of_view_um = 7958.72
row_count_pixels = 10640
column_count_pixels = 14192
data_type = "uint16"

[sample_stage_specs]
move_time_um = 0.025
backlash_reset_distance_um = 4

[daq_ao_names_to_channels]
etl = 1

[daq_driver_kwds]
dev_name = "Dev1"
samples_per_sec = 10000.0

[tiger_controller_driver_kwds]
com_port = "COM3"

[filter_wheel_kwds]
tiger_axis = 1

[estimates]
tiles_per_second = 15

[daq_driver_kwds.ao_channels]
etl = 0
camera = 1
stage = 2
488 = 3
638 = 4
561 = 5
405 = 6

[channel_specs.488]
driver = "Oxxius"
color = "blue"
hex_color = "#00ff92"
ao_channel = 3
disable_voltage = 0.0
enable_voltage = 5.0
buffer_time_s = 0.001

[channel_specs.561]
driver = "Oxxius"
color = "yellowgreen"
hex_color = "#c6ff00"
ao_channel = 5
disable_voltage = 0.0
enable_voltage = 5.0
buffer_time_s = 0.001

[channel_specs.405]
driver = "Oxxius"
color = "purple"
hex_color = "#000000"
ao_channel = 6
disable_voltage = 0.0
enable_voltage = 5.0
buffer_time_s = 0.001

[channel_specs.638]
driver = "Oxxius"
color = "red"
hex_color = "#000000"
ao_channel = 4
disable_voltage = 0.0
enable_voltage = 5.0
buffer_time_s = 0.001

[sample_pose_kwds.axis_map]
x = "y"
y = "z"
z = "x"

[channel_specs.488.camera]
delay_time_s = 0

[channel_specs.488.etl]
delay = 0.0
settling_time = 0.025
min_voltage = 2.37
max_voltage = 2.96
amplitude = 0.171
offset = 2.422
nonlinear = -0.007
interp_time_s = 0.5
buffer_time_s = 0.05

[channel_specs.488.gavlo_a]
setpoint = 0.0

[channel_specs.488.galvo_b]
setpoint = 0.0

[channel_specs.488.kwds]
port = "COMxx"

[channel_specs.561.camera]
delay_time_s = 0

[channel_specs.561.etl]
delay = 0.0
settling_time = 0.025
min_voltage = 2.37
max_voltage = 2.96
amplitude = 0.171
offset = 2.422
nonlinear = -0.007
interp_time_s = 0.5
buffer_time_s = 0.05

[channel_specs.561.gavlo_a]
setpoint = 0.0

[channel_specs.561.galvo_b]
setpoint = 0.0

[channel_specs.561.kwds]
port = "COMxx"

[channel_specs.405.camera]
delay_time_s = 0

[channel_specs.405.etl]
delay = 0.0
settling_time = 0.025
min_voltage = 2.37
max_voltage = 2.96
amplitude = 0.171
offset = 2.422
nonlinear = -0.007
interp_time_s = 0.5
buffer_time_s = 0.05

[channel_specs.405.gavlo_a]
setpoint = 0.0

[channel_specs.405.galvo_b]
setpoint = 0.0

[channel_specs.405.kwds]
port = "COMxx"

[channel_specs.638.camera]
delay_time_s = 0

[channel_specs.638.etl]
delay = 0.0
settling_time = 0.025
min_voltage = 2.37
max_voltage = 2.96
amplitude = 0.171
offset = 2.422
nonlinear = -0.007
interp_time_s = 0.5
buffer_time_s = 0.05

[channel_specs.638.gavlo_a]
setpoint = 0.0

[channel_specs.638.galvo_b]
setpoint = 0.0

[channel_specs.638.kwds]
port = "COMxx"
